spring:
  datasource:
    username: ${spring.datasource.username}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
  application:
    name: MsCuenta
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  #datasource:
    #  username: galva
      #hikari:
      #maximum-pool-size: 5
    #connection-timeout: 20000
    #url: jdbc:postgresql://localhost:5432/db_galva
    #password: '123456'
server:
  servlet:
    context-path: /MsCuenta
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#eureka:
    # instance:
    #instance-id: "${spring.application.name}:${random.value}"
    #client:
      #service-url:
      #defaultZone: http//localhost:8761/eueka/
